### ISSUE TITLE
Unity and Rider connection not working

### ISSUE THREAD

**Issue by ziomek64** [needle-mirror/com.unity.ide.rider#1]
As in the title Rider can't connect with Unity. I have newest package, tried different versions. It happened to me after I updated Rider, although i tried reinstalling and removing anything related to JetBrains from PC. Still not working. How do I actually make sure I connect Rider with Unity? It's such a random thing, I barely made it work last time, it was pure luck. On top of that there is this langversion that is wrong or something when compiling.

**Comment by marwie** [comment]
Hello, please report the issue to Jetbrains/Rider team on their official issue tracker: https://youtrack.jetbrains.com/issues/RIDER
